In [1]:
import numpy as np


In [2]:
array1 = np.array(range(30))


In [14]:
ans1=array1.reshape(5, 6)

In [29]:
print(ans1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [32]:
ans2=np.where(ans1/6==1)

In [31]:
print(ans2)

(array([1], dtype=int64), array([0], dtype=int64))
