In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [12]:
ans1=np.arange(0, 20, 1)

In [29]:
ans2=ans1[::2]

In [30]:
ans3=ans1[::3]

In [31]:
print(ans1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
print(ans2)

[ 0  2  4  6  8 10 12 14 16 18]


In [27]:
print(ans3)

[ 0  3  6  9 12 15 18]
